export const navBarItems=[
    {
        name:'Home',
        path:'/'
    },
    {
        name:'About',
        path:'/about'
    },
    {
        name:'Blog',
        path:'/blog'
    },
    {
        name:'Gallery',
        path:'/gallery'
    },
    {
        name:'Contact',
        path:'/contact'
    },
]